x-env-aliases:
  - &DEFAULT_ARGS
    NODE_REPO: "${NODE_REPO:-public.ecr.aws/docker/library/node}"
    NODE_TAG: "${NODE_TAG:-18.17.0-alpine3.17}"
  - &DEFAULT_API_ENVS
    NODE_ENV: "development"
    POSTGRES_HOST: "postgres"

version: '3.8'

services:
  api:
    build:
      context: .
      target: ${DOCKER_IMAGE_TARGET_API:-API}
      args:
        <<: *DEFAULT_ARGS
    restart: on-failure
    env_file:
      - .env
    environment:
      <<: *DEFAULT_API_ENVS
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_started
    networks:
      - default
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - '5050:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - default
    depends_on:
      - postgres

volumes:
  postgres-data:
    driver: local
  pgadmin-data:
    driver: local

networks:
  default:
